@startuml Juniper Flow

node generic as "Generic configuration JSON"
node juniper_tree as "Juniper configuration Node Tree"
node juniper as "Juniper Configuration"


generic <-> juniper_tree : JuniperConfigTranslator using JuniperDict
juniper_tree -> juniper : JuniperConfigGenerator
juniper -> juniper_tree : JuniperConfigParser

@enduml