@startuml Cisco Flow

node cisco as "Cisco Configuration"
node generic as "Generic Configuration JSON"
node cisco_tree as "Cisco Configuration Node Tree"

cisco -> cisco_tree : CiscoConfigParser
cisco_tree <-> generic : CiscoConfigTranslator using CiscoDict

cisco_tree -> cisco : CiscoConfigGenerator

@enduml