from anytree import Node, PreOrderIter
import re

""" @netconfparsers """


class ConfigParser:
    """ @brief interface for all network configuration parsers """
    def parse(self):
        pass


class CiscoConfigParser(ConfigParser):
    """ @brief class responsible for parsing cisco network configuration into a node tree """

    nodes = []
    interfaces = []
    root = None
    config = None
    COMMENT_REGEX = re.compile("[\s]*[!]")

    def __init__(self, filename):
        # --- open file and read it
        self.filename = filename
        self.fd = open(filename, "r")
        self.config = self.fd.readlines()
        # --- create root node
        self.root = Node("root")

    def parse(self):
        """ @brief parses the config file into a tree """
        indent = 0
        i = iter(self.config)
        parent = self.root
        while True:
            try:
                line = next(i).rstrip('\n')
                if self.COMMENT_REGEX.search(line):
                    continue
                if indent == (len(line) - len(line.lstrip(' ')) - 1):
                    parent = parent.children[-1]
                    Node(line.lstrip(' '), parent=parent)
                    indent = indent + 1
                elif indent == (len(line) - len(line.lstrip(' ')) + 1):
                    parent = parent.parent
                    Node(line.lstrip(' '), parent=parent)
                    indent = indent - 1
                else:
                    Node(line.lstrip(' '), parent=parent)
            except StopIteration:
                break
        return self.root


class JuniperConfigParser(ConfigParser):
    """ @brief class responsible for parsing juniper network configuration into a node tree """

    nodes = []
    interfaces = []
    root = None
    config = None
    COMMENT_REGEX = re.compile(".*[##]")

    def __init__(self, filename):
        self.filename = filename
        self.fd = open(filename, "r")
        self.config = self.fd.readlines()
        self.root = Node("root")

    def parse(self):
        """ @brief parses the config file into a tree """
        i = iter(self.config)
        parent = self.root
        while True:
            try:
                line = next(i)
                if line.startswith("##"):
                    continue
                if self.COMMENT_REGEX.search(line):
                    line = line.partition("##")[0]
                line = line.rstrip(" ;\n").lstrip(" ")

                if line == "}":
                    parent = parent.parent
                    continue
                if line.endswith("{"):
                    line = line.rstrip(" {")
                    Node(line, parent=parent)
                    parent = parent.children[-1]
                else:
                    Node(line, parent=parent)
            except StopIteration:
                break
        return self.root


class TreeToJuniperParser(ConfigParser):
    """class responsible for parsing node tree into Juniper configuration file"""
    config = []
    def __init__(self, root):
        self.root = root
        self.config.append("##Generated by \"Network Configuration Parser\"")

    def create_indent(self, length):
        i = 1
        tabs = ""
        indent = "\t"
        while i < length:
            tabs = tabs + indent
            i += 1
        return tabs

    def parse(self):
        current_depth = self.root.depth + 1
        for node in PreOrderIter(self.root):
            if (node.name == "root"):
                continue
            if node.depth < current_depth:
                difference = current_depth - node.depth
                while difference:
                    self.config.append(self.create_indent(current_depth-1) + "}")
                    difference -= 1
                    current_depth -= 1
            if node.is_leaf:
                self.config.append(self.create_indent(node.depth) + node.name + ";")
            else:
                self.config.append(self.create_indent(node.depth) + node.name + " {")
            current_depth = node.depth
        while current_depth > 1:
            self.config.append(self.create_indent(current_depth - 1) + "}")
            current_depth -= 1

    def write_to_file(self,filename):
        file = open(filename, "w")
        file.write("".join(str(n) + "\n" for n in self.config))
        file.close()

